apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: ubuntu-desktop-vm
spec:
  runStrategy: Always
  template:
    spec:
      domain:
        devices:
          disks:
          - name: containerdisk
            disk: {}
            bus: virtio
          - name: cloudinitdisk
            disk: {}
            bus: virtio
          - name: persistentdisk  # New persistent disk
            disk: {}
            bus: virtio
          graphics:
          - type: vnc
            listen:
              address: "0.0.0.0"
        resources:
          requests:
            memory: 4Gi
            cpu: 2
      volumes:
      - name: containerdisk
        containerDisk:
          image: quay.io/containerdisks/ubuntu:22.04
      - name: cloudinitdisk
        cloudInitNoCloud:
          userData: |-
            #cloud-config
            password: spud101!
            chpasswd: { expire: False }
            ssh_pwauth: True
            package_update: true
            packages:
              - ubuntu-desktop
              - xrdp
            runcmd:
              - mkfs.ext4 -F /dev/vdb
              - mkdir /persistent
              - mount /dev/vdb /persistent
              - echo "/dev/vdb /persistent ext4 defaults 0 0" >> /etc/fstab
              - systemctl enable xrdp
              - systemctl start xrdp
      - name: persistentdisk  # PVC definition
        persistentVolumeClaim:
          claimName: ubuntu-desktop-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ubuntu-desktop-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
